<a href="https://colab.research.google.com/github/sancoap/pytorch1/blob/main/Linear_Classifier.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [2]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import torch 
import torch.nn as nn

In [3]:
#This data is very popular in data science and is already packaged with scikit-learn
from sklearn.datasets import load_breast_cancer

In [4]:
data = load_breast_cancer()

In [5]:
type(data)

sklearn.utils.Bunch

In [6]:
#Bunch = Dictionary where you can treat keys as attributes
data.keys()

dict_keys(['data', 'target', 'target_names', 'DESCR', 'feature_names', 'filename'])

In [9]:
data

{'DESCR': '.. _breast_cancer_dataset:\n\nBreast cancer wisconsin (diagnostic) dataset\n--------------------------------------------\n\n**Data Set Characteristics:**\n\n    :Number of Instances: 569\n\n    :Number of Attributes: 30 numeric, predictive attributes and the class\n\n    :Attribute Information:\n        - radius (mean of distances from center to points on the perimeter)\n        - texture (standard deviation of gray-scale values)\n        - perimeter\n        - area\n        - smoothness (local variation in radius lengths)\n        - compactness (perimeter^2 / area - 1.0)\n        - concavity (severity of concave portions of the contour)\n        - concave points (number of concave portions of the contour)\n        - symmetry \n        - fractal dimension ("coastline approximation" - 1)\n\n        The mean, standard error, and "worst" or largest (mean of the three\n        largest values) of these features were computed for each image,\n        resulting in 30 features.  For

In [7]:
#check the input data
data.data.shape
#569 rows (N), 30 cols (D)


(569, 30)

In [8]:
data.target
#they are bunch of 0 and 1

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 1,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0,
       0, 0, 1, 0, 1, 1, 1, 1, 1, 0, 0, 1, 0, 0, 1, 1, 1, 1, 0, 1, 0, 0,
       1, 1, 1, 1, 0, 1, 0, 0, 1, 0, 1, 0, 0, 1, 1, 1, 0, 0, 1, 0, 0, 0,
       1, 1, 1, 0, 1, 1, 0, 0, 1, 1, 1, 0, 0, 1, 1, 1, 1, 0, 1, 1, 0, 1,
       1, 1, 1, 1, 1, 1, 1, 0, 0, 0, 1, 0, 0, 1, 1, 1, 0, 0, 1, 0, 1, 0,
       0, 1, 0, 0, 1, 1, 0, 1, 1, 0, 1, 1, 1, 1, 0, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 0, 1, 1, 1, 1, 0, 0, 1, 0, 1, 1, 0, 0, 1, 1, 0, 0, 1, 1, 1,
       1, 0, 1, 1, 0, 0, 0, 1, 0, 1, 0, 1, 1, 1, 0, 1, 1, 0, 0, 1, 0, 0,
       0, 0, 1, 0, 0, 0, 1, 0, 1, 0, 1, 1, 0, 1, 0, 0, 0, 0, 1, 1, 0, 0,
       1, 1, 1, 0, 1, 1, 1, 1, 1, 0, 0, 1, 1, 0, 1, 1, 0, 0, 1, 0, 1, 1,
       1, 1, 0, 1, 1, 1, 1, 1, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 1, 1, 1, 1, 1, 1, 0, 1, 0, 1, 1, 0, 1, 1, 0, 1, 0, 0, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 1, 1, 0,

In [9]:
data.target_names
#we can check what 0 or 1 means


array(['malignant', 'benign'], dtype='<U9')

In [10]:
data.target.shape
#you should have N labels , one for each N row

(569,)

In [11]:
data.feature_names

array(['mean radius', 'mean texture', 'mean perimeter', 'mean area',
       'mean smoothness', 'mean compactness', 'mean concavity',
       'mean concave points', 'mean symmetry', 'mean fractal dimension',
       'radius error', 'texture error', 'perimeter error', 'area error',
       'smoothness error', 'compactness error', 'concavity error',
       'concave points error', 'symmetry error',
       'fractal dimension error', 'worst radius', 'worst texture',
       'worst perimeter', 'worst area', 'worst smoothness',
       'worst compactness', 'worst concavity', 'worst concave points',
       'worst symmetry', 'worst fractal dimension'], dtype='<U23')

In [20]:
#split data into train and test
from sklearn.model_selection import train_test_split
X_train, X_test, Y_train, Y_test = train_test_split(data.data, data.target, test_size=0.33)
N,D = X_train.shape
print(X_train)

[[1.469e+01 1.398e+01 9.822e+01 ... 1.108e-01 2.827e-01 9.208e-02]
 [1.481e+01 1.470e+01 9.466e+01 ... 7.955e-02 2.334e-01 6.142e-02]
 [8.878e+00 1.549e+01 5.674e+01 ... 4.762e-02 2.434e-01 7.431e-02]
 ...
 [2.044e+01 2.178e+01 1.338e+02 ... 1.765e-01 2.609e-01 6.735e-02]
 [2.064e+01 1.735e+01 1.348e+02 ... 2.112e-01 2.689e-01 7.055e-02]
 [1.442e+01 1.654e+01 9.415e+01 ... 1.414e-01 3.053e-01 8.764e-02]]


In [21]:

#scale the data
#since output is a linear combination of inputs, you don't want ONE input to have a very large range
from sklearn.preprocessing import StandardScaler
scaler = StandardScaler()
X_train = scaler.fit_transform(X_train)
X_test = scaler.transform(X_test)

In [22]:
#sequenctial is type of a wrapper class for stacking the models
#we have D dimensions that serve as input to the linear model
#sigmoid will ensure that output is in the range of 0-1
model = nn.Sequential (
    nn.Linear(D,1),
    nn.Sigmoid()
)

In [23]:
#loss and optimizer
#BCE loss for classifier
#Adam is optimizer
criterion = nn.BCELoss()
optimizer = torch.optim.Adam(model.parameters())

In [24]:
#convert data into Torch Tensors
X_train = torch.from_numpy(X_train.astype(np.float32))
X_test = torch.from_numpy(X_test.astype(np.float32))
Y_train = torch.from_numpy(Y_train.astype(np.float32).reshape(-1,1))
Y_test = torch.from_numpy(Y_test.astype(np.float32).reshape(-1,1))


In [27]:
#Write code to train the models, same as before
#you need trial and error till loss per iteration looks right
n_epochs = 1000
train_losses = np.zeros(n_epochs)
test_losses = np.zeros(n_epochs)

for it in range(n_epochs):
  #zero the parameter gradients
  optimizer.zero_grad()
  #Forward Pass
  outputs = model(X_train)
  loss = criterion(outputs,Y_train)

  #backward pass
  loss.backward()
  optimizer.step()

  #calculate loss
  output_test = model(X_test)
  loss_test = criterion(output_test,Y_test)

  #record the loss
  train_losses[it] = loss.item()
  test_losses[it] = loss_test.item()

  #if we see test loss increasing during training, we know that our model is overfitting
  if (it +1) % 50  == 0:
    print(f'Epoch {it+1}/{n_epochs}, Train Loss: {loss.item():.4f}, Test Loss: {loss_test.item():.4f}')



Epoch 50/1000, Train Loss: 0.4635, Test Loss: 0.4814
Epoch 100/1000, Train Loss: 0.3494, Test Loss: 0.3794
Epoch 150/1000, Train Loss: 0.2835, Test Loss: 0.3174
Epoch 200/1000, Train Loss: 0.2399, Test Loss: 0.2752
Epoch 250/1000, Train Loss: 0.2087, Test Loss: 0.2450
Epoch 300/1000, Train Loss: 0.1854, Test Loss: 0.2228
Epoch 350/1000, Train Loss: 0.1675, Test Loss: 0.2060
Epoch 400/1000, Train Loss: 0.1532, Test Loss: 0.1928
Epoch 450/1000, Train Loss: 0.1416, Test Loss: 0.1822
Epoch 500/1000, Train Loss: 0.1321, Test Loss: 0.1734
Epoch 550/1000, Train Loss: 0.1241, Test Loss: 0.1661
Epoch 600/1000, Train Loss: 0.1173, Test Loss: 0.1599
Epoch 650/1000, Train Loss: 0.1115, Test Loss: 0.1547
Epoch 700/1000, Train Loss: 0.1064, Test Loss: 0.1501
Epoch 750/1000, Train Loss: 0.1019, Test Loss: 0.1461
Epoch 800/1000, Train Loss: 0.0979, Test Loss: 0.1426
Epoch 850/1000, Train Loss: 0.0944, Test Loss: 0.1395
Epoch 900/1000, Train Loss: 0.0912, Test Loss: 0.1368
Epoch 950/1000, Train Loss: 0

In [30]:
#Get accuracy
with torch.no_grad():
  p_train = model(X_train)
  p_train = np.round(p_train.numpy())
  train_accuracy = np.mean(Y_train.numpy() == p_train)

  p_test = model(X_test)
  p_test = np.round(p_test.numpy())
  test_accuracy = np.mean(Y_test.numpy() == p_test)
  print(f'Train accuracy: {train_accuracy:.4f},  Test accuracy: {test_accuracy:.4f}')

Train accuracy: 0.9843,  Test accuracy: 0.9628


In [31]:
#save model to a file and load the model
#this is an ordered dictionary, this has parameters of the model, with weight matrix and bias vector
model.state_dict()


OrderedDict([('0.weight',
              tensor([[-0.5313, -0.4953, -0.2456, -0.2906, -0.1558, -0.2539, -0.4492, -0.3292,
                       -0.1503,  0.3882, -0.5316, -0.0745, -0.3955, -0.5515,  0.2091,  0.1190,
                        0.1624, -0.1335,  0.2783,  0.4573, -0.2633, -0.3936, -0.2756, -0.2788,
                       -0.3948, -0.1755, -0.3720, -0.4678, -0.2839, -0.3225]])),
             ('0.bias', tensor([0.3511]))])

In [32]:
#save model to current dir
torch.save(model.state_dict(), 'mymodel.pt')


In [33]:
!ls

mymodel.pt  sample_data


In [34]:
#Load and evaluate the model to verify that we saved it correctly
#We need to instantiate our model before we load it, what? 
model2 = nn.Sequential (
   nn.Linear(D, 1),
   nn.Sigmoid()
)
model2.load_state_dict(torch.load('mymodel.pt'))

<All keys matched successfully>

In [36]:
#evalute the model, simply  checking accuracy again!
with torch.no_grad():
  p_train = model2(X_train)
  p_train = np.round(p_train.numpy())
  train_accuracy = np.mean(Y_train.numpy() == p_train)

  p_test = model2(X_test)
  p_test = np.round(p_test.numpy())
  test_accuracy = np.mean(Y_test.numpy() == p_test)
  print(f'Train accuracy: {train_accuracy:.4f},  Test accuracy: {test_accuracy:.4f}')

Train accuracy: 0.9843,  Test accuracy: 0.9628


In [37]:
#Download the model
from google.colab import files
files.download('mymodel.pt')

<IPython.core.display.Javascript object>

<IPython.core.display.Javascript object>